POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Chisom Udonsi",
    "email": "udonsichisom02@gmail.com",
    "phoneNumber": "+2347063265056",
    "location": "FearGod lodge, Umuchima",
    "password": "Test@1234"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "udonsichisom02@gmail.com",
    "password": "Test@1234"
}
