POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Chisom Udonsi",
    "email": "udonsichisom02@gmail.com",
    "phoneNumber": "+2347063265056",
    "location": "FearGod lodge, Umuchima",
    "password": "Test@1234"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "udonsichisom02@gmail.com",
    "password": "Test@1234"
}

###

POST http://localhost:5000/api/emergency
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTgyZTMwYjk0NmU5ZWFjMDhjMzkwOCIsImlhdCI6MTczODAyNjU0NH0.767kIy_Uu1bqLjlkwlKfHypn5wwlk0habt-MrzIJpdw

{
    "title": "Theft",
    "description": "Armed robbers are attacking my street",
    "location": "Posh view castle"
}

###

GET http://localhost:5000/api/emergency
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTgyZTMwYjk0NmU5ZWFjMDhjMzkwOCIsImlhdCI6MTczODAyNjU0NH0.767kIy_Uu1bqLjlkwlKfHypn5wwlk0habt-MrzIJpdw

###

PATCH http://localhost:5000/api/emergency/679830824ead77ab91048f73
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTgyZTMwYjk0NmU5ZWFjMDhjMzkwOCIsImlhdCI6MTczODAyNjU0NH0.767kIy_Uu1bqLjlkwlKfHypn5wwlk0habt-MrzIJpdw

###

GET http://localhost:5000/api/notification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTgyZTMwYjk0NmU5ZWFjMDhjMzkwOCIsImlhdCI6MTczODAyNjU0NH0.767kIy_Uu1bqLjlkwlKfHypn5wwlk0habt-MrzIJpdw

